### ISSUE TITLE
Interface Cleanup (v3.0)

### ISSUE THREAD

**Issue by FredKSchott** [FredKSchott/fflip#10]
This project has gone through a few different changes over the last two years, and looking back now I can see a few glaring issues with the interface. I'd like to add some new features to fflip over the next few weeks, but first I'd like to do a bit of cleanup:

1. Rename `express_route()` & `express_middleware()` to their lowerCamelCase equivalents. I was trying to be clever here by including an underscore to denote private within the express realm, but looking back now I have no idea why I thought that would make sense to anyone else.
2. Remove `express()` in favor of using `expressRoute()` & `expressMiddleware()` directly. In the future I'd like us to pull these out of the core library and build the library so that it can be extended for any framework.
3. Rename `userFeatures()` & `userHasFeature()` to `getFeaturesForUser()` & `isFeatureEnabledForUser()`. This will make room for `getFeatures()` & `isFeatureEnabled()` without the user object and new feature/criteria descriptions such as `$or`, `veto`, `default`.

All old method signatures should be deprecated for a major version before being completely removed in the next.

Thoughts?

**Comment by rosskukulinski** [comment]
Hey @FredKSchott - I'm excited to see you picking this project up again.  Its been a while since I've dug through the APIs, but I'm particularly interested in (2).  I use restify for almost all my projects and would love to move the middleware functionality out into separate modules so that you can choose between:

* fflip
* fflip-express
* fflip-restify
* fflip-hapi

etc

**Comment by FredKSchott** [comment]
:+1: That's exactly what I'm thinking, if there's enough interest. 

There's nothing too complex going on in there, although it will take a little work to pull out. I think the next step will be to make the `_features` & `_criteria` properties public and to start supporting them. I'll try to time that with the new feature/criteria descriptions to minimize thrash.

All that put together sounds like a pretty good v3.

**Comment by FredKSchott** [comment]
@rosskukulinski just made you a contributor, feel free to play around!

**Comment by FredKSchott** [comment]
New interface logic exists here: https://github.com/FredKSchott/fflip/tree/v3-interface

**Comment by FredKSchott** [comment]
@judikdavid Just found https://github.com/judikdavid/koa-fflip, awesome stuff! 

You might be interested in (2) as well to support koa as well as express, restify, etc. Are you still using this package?

**Comment by FredKSchott** [comment]
Resolved in #12
