### ISSUE TITLE
config method can be made asynchronous

### ISSUE THREAD

**Issue by mageshpandian91** [FredKSchott/fflip#18]
Initial loading of features in an asynchronous way can be improvised.

Let us assume **someAysnchronousFunction** is returning features loaded from redis

```
fflip.config({ criteria: {}, 
                     features: someAysnchronousFunction, 
                     reload: anyInterval });
fflip.isEnabledForUser(feature, user);  // This is returning null as the features are not yet loaded
``` 

can this be like

```
fflip.config({ criteria: {}, features: someAysnchronousFunction, reload: anyInterval }, function(){
  fflip.isEnabledForUser(feature, user); 
})
```

**Comment by ismriv** [comment]
I'm interested in this too.

@FredKSchott is this module still maintained? It's quite popular, but last commit is almost 2 years old. I can put together a PR if it would be merged and released.

**Comment by FredKSchott** [comment]
@ismriv definitely, I'd love some help! This has been too far down on my todo list unfortunately. Happy to review any PRs though if you're interested
